version: '3.8'

services:
  bs.presentation:
    build:
      context: ..
      dockerfile: src/BS.API/Dockerfile
    container_name: bs.api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=bs.db;Port=5432;Database=bs_db;Username=bs_user;Password=bs_password
    depends_on:
      - bs.db

  bs.db:
    image: postgres:16
    container_name: bs.db
    environment:
      POSTGRES_DB: bs_db
      POSTGRES_USER: bs_user
      POSTGRES_PASSWORD: bs_password
    ports:
      - "5432:5432"
    volumes:
      - bs_postgres_data:/var/lib/postgresql/data

volumes:
  bs_postgres_data:
